// Package detect auto-detects project configuration from manifest files,
// local binaries, environment files, and common project files without
// hardcoding knowledge of specific technology stacks.
package detect

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"env-doctor/internal/config"
)

// VersionEntry records a detected version constraint and the manifest source
// that produced it.
type VersionEntry struct {
	Version string // e.g. "8.x" or "1.21"
	Source  string // subdirectory path + manifest, e.g. "frontend/package.json"
}

// Detected holds the result of agnostic detection plus metadata used to
// annotate the generated YAML.
type Detected struct {
	Config       config.Config
	ToolComments map[string]string
	ToolSources  map[string]string
	FileComments map[string]string

	// New — multi-subdirectory tracking
	ToolSubdirs   map[string][]string // tool → all subdirectories where found
	ToolConflicts map[string][]VersionEntry
	EnvSubdirs    map[string][]string // env_var → subdirectories where .env found
	FileSubdirs   map[string][]string // file path → subdirectories where found
}

// Detect inspects the given directory and returns a configuration built from
// manifest files, local binaries, environment files, and common project files.
func Detect(dir string) (Detected, error) {
	d := Detected{
		Config:        newConfig(),
		ToolComments:  make(map[string]string),
		ToolSources:   make(map[string]string),
		FileComments:  make(map[string]string),
		ToolSubdirs:   make(map[string][]string),
		ToolConflicts: make(map[string][]VersionEntry),
		EnvSubdirs:    make(map[string][]string),
		FileSubdirs:   make(map[string][]string),
	}

	// Discover all scan targets: root first, then subdirectories.
	subdirs, err := collectSubdirs(dir, defaultSkipList)
	if err != nil {
		return Detected{}, err
	}
	scanTargets := append([]string{dir}, subdirs...)

	// 1. Extract tools from manifest files in every scan target.
	extractors := DefaultExtractors()
	for _, subdir := range scanTargets {
		subRel := relSubdir(dir, subdir)

		for _, ext := range extractors {
			seenPaths := make(map[string]struct{})
			for _, pattern := range ext.FilePatterns() {
				matches, err := filepath.Glob(filepath.Join(subdir, pattern))
				if err != nil {
					continue
				}
				for _, path := range matches {
					if _, ok := seenPaths[path]; ok {
						continue
					}
					seenPaths[path] = struct{}{}

					tools, err := ext.Extract(path)
					if err != nil {
						// Primary manifest files are required to parse correctly.
						if isPrimaryManifest(filepath.Base(path)) {
							return Detected{}, err
						}
						continue
					}
					source := sourceForExtractor(ext, path)
					comment := commentForExtractor(ext, path)
					for name, ver := range tools {
						d.ToolSubdirs[name] = append(d.ToolSubdirs[name], subRel)
						if _, exists := d.Config.Tools[name]; exists {
							continue
						}
						d.Config.Tools[name] = ver
						d.ToolSources[name] = source
						d.ToolComments[name] = comment
					}
				}
			}
		}
	}

	// 2. Extract environment variables from every scan target.
	_, envScanner, fileScanner := DefaultScanners()
	envSeen := make(map[string]struct{})
	for _, subdir := range scanTargets {
		subRel := relSubdir(dir, subdir)

		vars := envScanner.Scan(subdir)
		for _, name := range vars {
			d.EnvSubdirs[name] = append(d.EnvSubdirs[name], subRel)
			if _, exists := envSeen[name]; exists {
				continue
			}
			d.Config.Env = append(d.Config.Env, name)
			envSeen[name] = struct{}{}
		}
	}

	// 3. Find common project files in every scan target.
	fileSeen := make(map[string]struct{})
	for _, subdir := range scanTargets {
		subRel := relSubdir(dir, subdir)

		files := fileScanner.Scan(subdir)
		for _, f := range files {
			relPath := f
			if subRel != "" {
				relPath = filepath.Join(subRel, f)
			}
			d.FileSubdirs[relPath] = append(d.FileSubdirs[relPath], subRel)
			if _, exists := fileSeen[relPath]; exists {
				continue
			}
			d.Config.Files = append(d.Config.Files, relPath)
			fileSeen[relPath] = struct{}{}

			if isCommonFile(f) {
				d.FileComments[relPath] = "Common project file"
			} else {
				d.FileComments[relPath] = "Found in project"
			}
		}
	}

	if len(d.Config.Tools) == 0 && len(d.Config.Env) == 0 && len(d.Config.Files) == 0 {
		return Detected{}, fmt.Errorf("no recognizable project found in %q; run 'env-doctor init' without --auto for a sample config", dir)
	}

	return d, nil
}

// Generate renders a human-readable .env-doctor.yaml from a Detected value.
func Generate(d Detected) (string, error) {
	sort.Strings(d.Config.Env)

	var b strings.Builder
	fmt.Fprintf(&b, "version: \"1\"\n\n")
	fmt.Fprintf(&b, "# Auto-generated by env-doctor init --auto\n")
	fmt.Fprintf(&b, "# Detected tools from manifest files\n\n")

	// Tools grouped by source.
	fmt.Fprintf(&b, "tools:\n")
	if len(d.Config.Tools) == 0 {
		fmt.Fprintf(&b, "  {}\n")
	} else {
		toolNames := make([]string, 0, len(d.Config.Tools))
		for name := range d.Config.Tools {
			toolNames = append(toolNames, name)
		}
		sort.Strings(toolNames)

		groups := groupBySource(toolNames, d.ToolSources)
		firstGroup := true
		for _, group := range groups {
			if !firstGroup {
				fmt.Fprintf(&b, "\n")
			}
			firstGroup = false
			fmt.Fprintf(&b, "  # %s\n", group.source)
			for _, name := range group.names {
				fmt.Fprintf(&b, "  %q: %q", name, d.Config.Tools[name])
				if cmt, ok := d.ToolComments[name]; ok && cmt != "" {
					fmt.Fprintf(&b, "  # %s", cmt)
				}
				fmt.Fprintf(&b, "\n")
			}
		}
	}

	// Env
	fmt.Fprintf(&b, "\nenv:\n")
	if len(d.Config.Env) == 0 {
		fmt.Fprintf(&b, "  []\n")
	} else {
		for _, name := range d.Config.Env {
			fmt.Fprintf(&b, "  - %s\n", name)
		}
	}

	// Files grouped by source.
	fmt.Fprintf(&b, "\nfiles:\n")
	if len(d.Config.Files) == 0 {
		fmt.Fprintf(&b, "  []\n")
	} else {
		common := make([]string, 0)
		found := make([]string, 0)
		for _, f := range d.Config.Files {
			if isCommonFile(f) {
				common = append(common, f)
			} else {
				found = append(found, f)
			}
		}
		if len(common) > 0 {
			fmt.Fprintf(&b, "  # Common project files\n")
			for _, f := range common {
				fmt.Fprintf(&b, "  - %s\n", f)
			}
		}
		if len(found) > 0 {
			if len(common) > 0 {
				fmt.Fprintf(&b, "\n")
			}
			fmt.Fprintf(&b, "  # Found in project\n")
			for _, f := range found {
				fmt.Fprintf(&b, "  - %s\n", f)
			}
		}
	}

	// Ports placeholder.
	fmt.Fprintf(&b, "\n# Add port checks manually:\n")
	fmt.Fprintf(&b, "# ports:\n")
	fmt.Fprintf(&b, "#   3000: free\n")

	return b.String(), nil
}

func newConfig() config.Config {
	return config.Config{
		Version: "1",
		Tools:   make(map[string]string),
		Ports:   make(map[int]string),
	}
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

type sourceGroup struct {
	source string
	names  []string
}

func groupBySource(names []string, sources map[string]string) []sourceGroup {
	order := []string{
		"Extracted from package.json",
		"Extracted from go.mod",
		"Extracted from requirements.txt",
		"Extracted from pyproject.toml",
		"Extracted from other files",
		"Extracted from local binaries",
	}
	index := make(map[string]int)
	for i, s := range order {
		index[s] = i
	}

	groups := make(map[string]*sourceGroup)
	orderedKeys := make([]string, 0)
	for _, name := range names {
		source := sources[name]
		if source == "" {
			source = "Extracted from other files"
		}
		if _, ok := groups[source]; !ok {
			groups[source] = &sourceGroup{source: source}
			orderedKeys = append(orderedKeys, source)
		}
		groups[source].names = append(groups[source].names, name)
	}

	sort.SliceStable(orderedKeys, func(i, j int) bool {
		ii, oki := index[orderedKeys[i]]
		ji, okj := index[orderedKeys[j]]
		if oki && okj {
			return ii < ji
		}
		if oki {
			return true
		}
		if okj {
			return false
		}
		return orderedKeys[i] < orderedKeys[j]
	})

	result := make([]sourceGroup, 0, len(orderedKeys))
	for _, key := range orderedKeys {
		g := groups[key]
		sort.Strings(g.names)
		result = append(result, *g)
	}
	return result
}

func sourceForExtractor(ext ManifestExtractor, path string) string {
	switch ext.(type) {
	case *JSONExtractor:
		return "Extracted from manifest file"
	case *GoModExtractor:
		return "Extracted from manifest file"
	case *PythonExtractor:
		return "Extracted from manifest file"
	case *GenericExtractor:
		return "Extracted from other files"
	default:
		return "Extracted from project files"
	}
}

func commentForExtractor(ext ManifestExtractor, path string) string {
	switch ext.(type) {
	case *JSONExtractor:
		return "From dependency manifest"
	case *GoModExtractor:
		return "From dependency manifest"
	case *PythonExtractor:
		return "From dependency manifest"
	case *GenericExtractor:
		switch filepath.Base(path) {
		case "docker-compose.yml", "docker-compose.yaml":
			return "Found in project"
		default:
			return "Found in project"
		}
	default:
		return "Found in project"
	}
}

func isPrimaryManifest(name string) bool {
	switch name {
	case "package.json", "go.mod", "requirements.txt", "pyproject.toml":
		return true
	}
	return false
}

func relSubdir(dir, subdir string) string {
	rel, _ := filepath.Rel(dir, subdir)
	if rel == "." {
		return ""
	}
	return rel
}

func isCommonFile(name string) bool {
	common := map[string]bool{
		".env":                true,
		".env.example":        true,
		".gitignore":          true,
		"README.md":           true,
		"README":              true,
		"LICENSE":             true,
		"Makefile":            true,
		"Dockerfile":          true,
		"docker-compose.yml":  true,
		"docker-compose.yaml": true,
		"package.json":        true,
		"go.mod":              true,
		"main.go":             true,
		"requirements.txt":    true,
		"pyproject.toml":      true,
	}
	return common[name]
}
